apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-hostname
  name: node-hostname
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hostname
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-hostname
    spec:
      containers:
      - image: adeniyistephen/node-web-app:0.1
        imagePullPolicy: Always
        name: node-web-app
        resources: {}
        ports:
          - containerPort: 3000
            name: http
      terminationGracePeriodSeconds: 30
