apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-hostname
  name: node-hostname-svc
  namespace: default
spec:
  ports:
  - nodePort: 31357
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-hostname
  type: NodePort
